networks:
  ecappNet:
    external: true

volumes:
  pgdata:
  
services:
    postgres:
      container_name: postgres
      image: postgres:latest
      ports:
        - 5432:5436
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=ecapp
      networks:
        - ecappNet
      
    shopdata-service:
      container_name: shopdataservice
      image: shopdataservice:latest
      ports:
        - 8091:8091
      networks:
        - ecappNet

