networks:
  ecappNet:
    external: true

volumes:
  pgdata:
  
services:
    postgres:
      container_name: postgres
      image: postgres:latest
      ports:
        - 5432:5436
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=ecapp
      networks:
        - ecappNet
      
    shopdata-jenkins:
      container_name: shopdata-jenkins
      image: gagan163264/shopdatajenkins:19-ae6cc9f41adb0b5097f7a480ae365a40b0fa3657
      ports:
        - 8091:8091
      networks:
        - ecappNet

