pipeline {
    agent any
    environment { 
        NAME = "shopdatajenkins"
        VERSION = "${env.BUILD_ID}-${env.GIT_COMMIT}"
        IMAGE = "${NAME}:${VERSION}"
        DOCKERHUB_CREDS = credentials('99e768b8-3323-4614-9671-0ad00c63c7ea')
    }
    stages {
        stage('Build') {
            steps {
                dir("shopdataservice") {
                    echo "Running ${VERSION} on ${env.JENKINS_URL}"
                    bat "./gradlew clean bootJar"
                    echo "Building Docker image ${IMAGE}"
                    bat "docker build -t ${IMAGE} ."
                    bat "docker tag ${IMAGE} ${DOCKERHUB_CREDS_USR}/${IMAGE}"
                    bat "docker push ${DOCKERHUB_CREDS_USR}/${IMAGE}"
                }
            }
        }
        stage('Test') {
            steps {
                echo 'NO tests defined'
            }
        }
        stage('Deploy') {
            steps {
                echo "Pushing Docker image ${IMAGE} to DockerHub"
                echo "${DOCKERHUB_CREDS_USR} ${DOCKERHUB_CREDS_PSW}"
            }
        }
    }
}